addSbtPlugin("de.heikoseeberger"  % "sbt-header"     % "5.10.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"   % "2.5.2")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"  % "1.6.1")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"    % "0.6.4")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"        % "0.4.5")
addSbtPlugin("org.scalameta"      % "sbt-mdoc"       % "2.3.7")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release" % "1.5.12")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"   % "0.11.0")
