// Generated by tools/antlr-import/convert.py from Apache Cassandra's Parser.g
// (see tools/antlr-import/upstream/VERSION). DO NOT EDIT BY HAND.
//
// Recognizer-only: every embedded Java action, `returns [...]`, rule argument
// and syntactic predicate from the upstream ANTLR3 grammar has been stripped.

parser grammar CqlParser;

options {
    tokenVocab = CqlLexer;
}

// Entry rule (mirrors Cassandra's `query` in Cql.g). CqlValidator calls root().
root
    : cqlStatement (';')* EOF
    ;

cqlStatement

    :  selectStatement
    |  insertStatement
    |  updateStatement
    |  batchStatement
    |  deleteStatement
    |  useStatement
    |  truncateStatement
    |  createKeyspaceStatement
    |  createTableStatement
    | createIndexStatement
    | dropKeyspaceStatement
    | dropTableStatement
    | dropIndexStatement
    | alterTableStatement
    | alterKeyspaceStatement
    | grantPermissionsStatement
    | revokePermissionsStatement
    | listPermissionsStatement
    | createUserStatement
    | alterUserStatement
    | dropUserStatement
    | listUsersStatement
    | createTriggerStatement
    | dropTriggerStatement
    | createTypeStatement
    | alterTypeStatement
    | dropTypeStatement
    | createFunctionStatement
    | dropFunctionStatement
    | createAggregateStatement
    | dropAggregateStatement
    | createRoleStatement
    | alterRoleStatement
    | dropRoleStatement
    | listRolesStatement
    | grantRoleStatement
    | revokeRoleStatement
    | createMaterializedViewStatement
    | dropMaterializedViewStatement
    | alterMaterializedViewStatement
    | describeStatement
    | addIdentityStatement
    | dropIdentityStatement
    ;

/*
 * USE <KEYSPACE>;
 */
useStatement
    : K_USE keyspaceName
    ;

/**
 * SELECT <expression>
 * FROM <CF>
 * WHERE KEY = "key1" AND COL > 1 AND COL < 100
 * LIMIT <NUMBER>;
 */
selectStatement

    : K_SELECT
        // json is a valid column name. By consequence, we need to resolve the ambiguity for "json - json"
      (  K_JSON  )? selectClause
      K_FROM columnFamilyName
      ( K_WHERE whereClause )?
      ( K_GROUP K_BY groupByClause ( ',' groupByClause )* )?
      ( K_ORDER K_BY orderByClause ( ',' orderByClause )* )?
      ( K_PER K_PARTITION K_LIMIT intValue  )?
      ( K_LIMIT intValue  )?
      ( K_ALLOW K_FILTERING   )?

    ;

selectClause

    // distinct is a valid column name. By consequence, we need to resolve the ambiguity for "distinct - distinct"
    :  K_DISTINCT selectors
    | selectors
    ;

selectors
    : selector  (',' selector )*
    | '*'
    ;

selector

    : unaliasedSelector (K_AS noncol_ident )?
    ;

unaliasedSelector
    : selectionAddition
    ;

selectionAddition
    :   selectionMultiplication
        ( '+' selectionMultiplication
        | '-' selectionMultiplication
        )*
    ;

selectionMultiplication
    :   selectionGroup
        ( '*' selectionGroup
        | '/' selectionGroup
        | '%' selectionGroup
        )*
    ;

selectionGroup
    :   selectionGroupWithField
    | selectionGroupWithoutField
    | '-' selectionGroup
    ;

selectionGroupWithField
    : selectionGroupWithoutField selectorModifier
    ;

selectorModifier
    : fieldSelectorModifier selectorModifier
    | '[' collectionSubSelection ']' selectorModifier
    |
    ;

fieldSelectorModifier
    : '.' fident
    ;

collectionSubSelection

    : ( term (  RANGE (term)? )?
      | RANGE  term
      )
     ;

selectionGroupWithoutField

    : simpleUnaliasedSelector
    |  selectionTypeHint
    | selectionTupleOrNestedSelector
    | selectionList
    | selectionMapOrSet
    // UDTs are equivalent to maps from the syntax point of view, so the final decision will be done in Selectable.WithMapOrUdt
    ;

selectionTypeHint
    : '(' comparatorType ')' selectionGroupWithoutField
    ;

selectionList

    : '[' ( unaliasedSelector  ( ',' unaliasedSelector  )* )? ']'
    ;

selectionMapOrSet
    : '{' unaliasedSelector ( selectionMap  | selectionSet ) '}'
    | '{' '}'
    ;

selectionMap

      : ':' unaliasedSelector    ( ',' unaliasedSelector ':' unaliasedSelector  )*
      ;

selectionSet

      : ( ',' unaliasedSelector  )*
      ;

selectionTupleOrNestedSelector

    : '(' unaliasedSelector  (',' unaliasedSelector  )* ')'
    ;

/*
 * A single selection. The core of it is selecting a column, but we also allow any term and function, as well as
 * sub-element selection for UDT.
 */
simpleUnaliasedSelector
    : sident
    | selectionLiteral
    | selectionFunction
    ;

selectionFunction
    : K_COUNT        '(' '*' ')'
    | K_MAXWRITETIME '(' sident selectorModifier ')'
    | K_WRITETIME    '(' sident selectorModifier ')'
    | K_TTL          '(' sident selectorModifier ')'
    | K_CAST         '(' unaliasedSelector K_AS native_type ')'
    | functionName selectionFunctionArgs
    ;

selectionLiteral
    : constant
    | K_NULL
    ;

selectionFunctionArgs

    : '(' (unaliasedSelector
          ( ',' unaliasedSelector  )*)?
      ')'
    ;

sident
    : IDENT
    | QUOTED_NAME
    | unreserved_keyword
    ;

whereClause

    : relationOrExpression (K_AND relationOrExpression)*
    ;

relationOrExpression
    : relation
    | customIndexExpression
    ;

customIndexExpression

    : 'expr(' idxName ',' term ')'
    ;

orderByClause

    : cident (K_ANN K_OF term)? (K_ASC | K_DESC )?

    ;

groupByClause
    : unaliasedSelector
    ;

/**
 * INSERT INTO <CF> (<column>, <column>, <column>, ...)
 * VALUES (<value>, <value>, <value>, ...)
 * USING TIMESTAMP <long>;
 *
 */
insertStatement
    : K_INSERT K_INTO columnFamilyName
        ( normalInsertStatement
        | K_JSON jsonInsertStatement )
    ;

normalInsertStatement

    : '(' cident   ( ',' cident  )* ')'
      K_VALUES
      '(' term  ( ',' term  )* ')'
      ( K_IF K_NOT K_EXISTS  )?
      ( usingClause )?

    ;

jsonInsertStatement

    : jsonValue
      ( K_DEFAULT ( K_NULL | (  K_UNSET) ) )?
      ( K_IF K_NOT K_EXISTS  )?
      ( usingClause )?

    ;

jsonValue
    : STRING_LITERAL
    | ':' noncol_ident
    | QMARK
    ;

usingClause
    : K_USING usingClauseObjective ( K_AND usingClauseObjective )*
    ;

usingClauseObjective
    : K_TIMESTAMP intValue
    | K_TTL intValue
    ;

/**
 * UPDATE <CF>
 * USING TIMESTAMP <long>
 * SET name1 = value1, name2 = value2
 * WHERE key = value;
 * [IF (EXISTS | name = value, ...)];
 */
updateStatement

    : K_UPDATE columnFamilyName
      ( usingClause )?
      K_SET columnOperation (',' columnOperation)*
      K_WHERE whereClause
      ( K_IF ( K_EXISTS  | updateConditions ))?

    ;

updateConditions

    : columnCondition ( K_AND columnCondition )*
    ;

/**
 * DELETE name1, name2
 * FROM <CF>
 * USING TIMESTAMP <long>
 * WHERE KEY = keyname
   [IF (EXISTS | name = value, ...)];
 */
deleteStatement

    : K_DELETE ( deleteSelection  )?
      K_FROM columnFamilyName
      ( usingClauseDelete )?
      K_WHERE whereClause
      ( K_IF ( K_EXISTS  | updateConditions ))?

    ;

deleteSelection
    :
          deleteOp
          (',' deleteOp )*
    ;

deleteOp
    : cident
    | cident '[' term ']'
    | cident '.' fident
    ;

usingClauseDelete
    : K_USING K_TIMESTAMP intValue
    ;

/**
 * BEGIN BATCH
 *   UPDATE <CF> SET name1 = value1 WHERE KEY = keyname1;
 *   UPDATE <CF> SET name2 = value2 WHERE KEY = keyname2;
 *   UPDATE <CF> SET name3 = value3 WHERE KEY = keyname3;
 *   ...
 * APPLY BATCH
 *
 * OR
 *
 * BEGIN BATCH
 *   INSERT INTO <CF> (KEY, <name>) VALUES ('<key>', '<value>');
 *   INSERT INTO <CF> (KEY, <name>) VALUES ('<key>', '<value>');
 *   ...
 * APPLY BATCH
 *
 * OR
 *
 * BEGIN BATCH
 *   DELETE name1, name2 FROM <CF> WHERE key = <key>
 *   DELETE name3, name4 FROM <CF> WHERE key = <key>
 *   ...
 * APPLY BATCH
 */
batchStatement

    : K_BEGIN
      ( K_UNLOGGED  | K_COUNTER  )?
      K_BATCH ( usingClause )?
          ( batchStatementObjective ';'?  )*
      K_APPLY K_BATCH

    ;

batchStatementObjective
    : insertStatement
    | updateStatement
    | deleteStatement
    ;

createAggregateStatement

    : K_CREATE (K_OR K_REPLACE )?
      K_AGGREGATE
      (K_IF K_NOT K_EXISTS )?
      functionName
      '('
        (
          comparatorType
          ( ',' comparatorType  )*
        )?
      ')'
      K_SFUNC  allowedFunctionName
      K_STYPE  comparatorType
      (
        K_FINALFUNC  allowedFunctionName
      )?
      (
        K_INITCOND  term
      )?

    ;

dropAggregateStatement

    : K_DROP K_AGGREGATE
      (K_IF K_EXISTS  )?
      functionName
      (
        '('
          (
            comparatorType
            ( ',' comparatorType  )*
          )?
        ')'

      )?

    ;

createFunctionStatement

    : K_CREATE (K_OR K_REPLACE )?
      K_FUNCTION
      (K_IF K_NOT K_EXISTS )?
      functionName
      '('
        (
          noncol_ident comparatorType
          ( ',' noncol_ident comparatorType  )*
        )?
      ')'
      ( (K_RETURNS K_NULL) | (K_CALLED )) K_ON K_NULL K_INPUT
      K_RETURNS  comparatorType
      K_LANGUAGE  IDENT
      K_AS  STRING_LITERAL

    ;

dropFunctionStatement

    : K_DROP K_FUNCTION
      (K_IF K_EXISTS  )?
      functionName
      (
        '('
          (
            comparatorType
            ( ',' comparatorType  )*
          )?
        ')'

      )?

    ;

/**
 * CREATE KEYSPACE [IF NOT EXISTS] <KEYSPACE> WITH attr1 = value1 AND attr2 = value2;
 */
createKeyspaceStatement

    : K_CREATE K_KEYSPACE (K_IF K_NOT K_EXISTS  )? keyspaceName
      K_WITH properties
    ;

/**
 * CREATE TABLE [IF NOT EXISTS] <CF> (
 *     <name1> <type>,
 *     <name2> <type>,
 *     <name3> <type>
 * ) WITH <property> = <value> AND ...;
 */
createTableStatement

    : K_CREATE K_COLUMNFAMILY (K_IF K_NOT K_EXISTS  )?
      columnFamilyName
      tableDefinition
    ;

tableDefinition
    : '(' tableColumns ( ',' tableColumns? )* ')'
      ( K_WITH tableProperty ( K_AND tableProperty )*)?
    ;

tableColumns

    : ident comparatorType (K_STATIC )? (columnMask)?
        (K_PRIMARY K_KEY )?
    | K_PRIMARY K_KEY '(' tablePartitionKey (',' ident  )* ')'
    ;

columnMask

    : K_MASKED K_WITH functionName columnMaskArguments
    | K_MASKED K_WITH K_DEFAULT
    ;

columnMaskArguments
    : '('  ')' | '(' term  (',' term )* ')'
    ;

tablePartitionKey

    : ident
    | '(' ident  ( ',' ident  )* ')'
    ;

tableProperty
    : property
    | K_COMPACT K_STORAGE
    | K_CLUSTERING K_ORDER K_BY '(' tableClusteringOrder (',' tableClusteringOrder)* ')'
    ;

tableClusteringOrder

    : ident (K_ASC | K_DESC  )
    ;

/**
 * CREATE TYPE foo (
 *    <name1> <type1>,
 *    <name2> <type2>,
 *    ....
 * )
 */
createTypeStatement

    : K_CREATE K_TYPE (K_IF K_NOT K_EXISTS  )?
         userTypeName
         '(' typeColumns ( ',' typeColumns? )* ')'
    ;

typeColumns
    : fident comparatorType
    ;

/**
 * CREATE INDEX [IF NOT EXISTS] [indexName] ON <columnFamily> (<columnName>);
 * CREATE CUSTOM INDEX [IF NOT EXISTS] [indexName] ON <columnFamily> (<columnName>) USING <indexClass>;
 */
createIndexStatement

    : K_CREATE (K_CUSTOM )? K_INDEX (K_IF K_NOT K_EXISTS  )?
        (idxName)? K_ON columnFamilyName '(' (indexIdent (',' indexIdent)*)? ')'
        (K_USING STRING_LITERAL )?
        (K_WITH properties)?

    ;

indexIdent
    : cident
    | K_VALUES '(' cident ')'
    | K_KEYS '(' cident ')'
    | K_ENTRIES '(' cident ')'
    | K_FULL '(' cident ')'
    ;

/**
 * CREATE MATERIALIZED VIEW <viewName> AS
 *  SELECT <columns>
 *  FROM <CF>
 *  WHERE <pkColumns> IS NOT NULL
 *  PRIMARY KEY (<pkColumns>)
 *  WITH <property> = <value> AND ...;
 */
createMaterializedViewStatement

    : K_CREATE K_MATERIALIZED K_VIEW (K_IF K_NOT K_EXISTS )? columnFamilyName K_AS
        K_SELECT selectors K_FROM columnFamilyName
        (K_WHERE whereClause)?

        viewPrimaryKey
        ( K_WITH viewProperty ( K_AND viewProperty )*)?
    ;

viewPrimaryKey
    : K_PRIMARY K_KEY '(' viewPartitionKey (',' ident  )* ')'
    ;

viewPartitionKey

    : ident
    | '(' ident  ( ',' ident  )* ')'
    ;

viewProperty
    : property
    | K_COMPACT K_STORAGE
    | K_CLUSTERING K_ORDER K_BY '(' viewClusteringOrder (',' viewClusteringOrder)* ')'
    ;

viewClusteringOrder

    : ident (K_ASC | K_DESC  )
    ;

/**
 * CREATE TRIGGER triggerName ON columnFamily USING 'triggerClass';
 */
createTriggerStatement

    : K_CREATE K_TRIGGER (K_IF K_NOT K_EXISTS  )? (ident)
        K_ON columnFamilyName K_USING STRING_LITERAL

    ;

/**
 * DROP TRIGGER [IF EXISTS] triggerName ON columnFamily;
 */
dropTriggerStatement

    : K_DROP K_TRIGGER (K_IF K_EXISTS  )? (ident) K_ON columnFamilyName

    ;

/**
 * ALTER KEYSPACE [IF EXISTS] <KS> WITH <property> = <value>;
 */
alterKeyspaceStatement

    : K_ALTER K_KEYSPACE (K_IF K_EXISTS  )? keyspaceName
        K_WITH properties
    ;

/**
 * ALTER TABLE <table> ALTER <column> TYPE <newtype>;
 * ALTER TABLE [IF EXISTS] <table> ALTER [IF EXISTS] <column> MASKED WITH <maskFunction>);
 * ALTER TABLE [IF EXISTS] <table> ALTER [IF EXISTS] <column> DROP MASKED;
 * ALTER TABLE [IF EXISTS] <table> ADD [IF NOT EXISTS] <column> <newtype> <maskFunction>; | ALTER TABLE [IF EXISTS] <table> ADD [IF NOT EXISTS] (<column> <newtype> <maskFunction>, <column1> <newtype1>  <maskFunction1>..... <column n> <newtype n>  <maskFunction n>)
 * ALTER TABLE [IF EXISTS] <table> DROP [IF EXISTS] <column>; | ALTER TABLE [IF EXISTS] <table> DROP [IF EXISTS] ( <column>,<column1>.....<column n>)
 * ALTER TABLE [IF EXISTS] <table> RENAME [IF EXISTS] <column> TO <column>;
 * ALTER TABLE [IF EXISTS] <table> WITH <property> = <value>;
 */
alterTableStatement

    : K_ALTER K_COLUMNFAMILY (K_IF K_EXISTS  )?
      columnFamilyName
      (
        K_ALTER cident K_TYPE comparatorType

      | K_ALTER ( K_IF K_EXISTS  )? cident
              ( columnMask
              | K_DROP K_MASKED  )

      | K_ADD ( K_IF K_NOT K_EXISTS  )?
              (        ident  comparatorType  isStaticColumn (columnMask)?
               | ('('  ident comparatorType isStaticColumn (columnMask)?
                 ( ',' ident comparatorType isStaticColumn (columnMask)?  )* ')') )

      | K_DROP ( K_IF K_EXISTS  )?
               (       ident
               | ('('  ident
                 ( ',' ident  )* ')') )
               ( K_USING K_TIMESTAMP INTEGER  )?

      | K_RENAME ( K_IF K_EXISTS  )?
               (        ident K_TO ident
                ( K_AND ident K_TO ident  )* )

      | K_DROP K_COMPACT K_STORAGE

      | K_WITH properties
      )
    ;

isStaticColumn

    : (K_STATIC )?
    ;

alterMaterializedViewStatement

    : K_ALTER K_MATERIALIZED K_VIEW (K_IF K_EXISTS  )? columnFamilyName
          K_WITH properties

    ;

/**
 * ALTER TYPE [IF EXISTS] <name> ALTER <field> TYPE <newtype>;
 * ALTER TYPE [IF EXISTS] <name> ADD [IF NOT EXISTS]<field> <newtype>;
 * ALTER TYPE [IF EXISTS] <name> RENAME [IF EXISTS] <field> TO <newtype> AND ...;
 */
alterTypeStatement

    : K_ALTER K_TYPE (K_IF K_EXISTS  )? userTypeName
      (
        K_ALTER   fident K_TYPE comparatorType

      | K_ADD (K_IF K_NOT K_EXISTS  )?     fident comparatorType

      | K_RENAME (K_IF K_EXISTS  )? fident K_TO fident
         ( K_AND fident K_TO fident         )*
      )
    ;

/**
 * DROP KEYSPACE [IF EXISTS] <KSP>;
 */
dropKeyspaceStatement

    : K_DROP K_KEYSPACE (K_IF K_EXISTS  )? keyspaceName
    ;

/**
 * DROP TABLE [IF EXISTS] <table>;
 */
dropTableStatement

    : K_DROP K_COLUMNFAMILY (K_IF K_EXISTS  )? columnFamilyName
    ;

/**
 * DROP TYPE <name>;
 */
dropTypeStatement

    : K_DROP K_TYPE (K_IF K_EXISTS  )? userTypeName
    ;

/**
 * DROP INDEX [IF EXISTS] <INDEX_NAME>
 */
dropIndexStatement

    : K_DROP K_INDEX (K_IF K_EXISTS  )? indexName

    ;

/**
 * DROP MATERIALIZED VIEW [IF EXISTS] <view_name>
 */
dropMaterializedViewStatement

    : K_DROP K_MATERIALIZED K_VIEW (K_IF K_EXISTS  )? columnFamilyName

    ;

/**
  * TRUNCATE <CF>;
  */
truncateStatement
    : K_TRUNCATE (K_COLUMNFAMILY)? columnFamilyName
    ;

/**
 * GRANT <permission>[, <permission>]* | ALL ON <resource> TO <rolename>
 */
grantPermissionsStatement
    : K_GRANT
          permissionOrAll
      K_ON
          resource
      K_TO
          userOrRoleName

    ;

/**
 * REVOKE <permission>[, <permission>]* | ALL ON <resource> FROM <rolename>
 */
revokePermissionsStatement
    : K_REVOKE
          permissionOrAll
      K_ON
          resource
      K_FROM
          userOrRoleName

    ;

/**
 * GRANT ROLE <rolename> TO <grantee>
 */
grantRoleStatement
    : K_GRANT
          userOrRoleName
      K_TO
          userOrRoleName

    ;

/**
 * REVOKE ROLE <rolename> FROM <revokee>
 */
revokeRoleStatement
    : K_REVOKE
          userOrRoleName
      K_FROM
          userOrRoleName

    ;

listPermissionsStatement

    : K_LIST
          permissionOrAll
      ( K_ON resource  )?
      ( K_OF roleName )?
      ( K_NORECURSIVE  )?

    ;

permission
    : (K_CREATE | K_ALTER | K_DROP | K_SELECT | K_MODIFY | K_AUTHORIZE | K_DESCRIBE | K_EXECUTE | K_UNMASK | K_SELECT_MASKED)

    ;

permissionOrAll
    : K_ALL ( K_PERMISSIONS )?
    | permission ( K_PERMISSION )?  ( ',' permission ( K_PERMISSION )?  )*
    ;

resource
    : dataResource
    | roleResource
    | functionResource
    | jmxResource
    ;

dataResource
    : K_ALL K_KEYSPACES
    | K_KEYSPACE  keyspaceName
    | ( K_COLUMNFAMILY )?  columnFamilyName
    | K_ALL K_TABLES K_IN K_KEYSPACE  keyspaceName
    ;

jmxResource
    : K_ALL K_MBEANS
    // when a bean name (or pattern) is supplied, validate that it's a legal ObjectName
    // also, just to be picky, if the "MBEANS" form is used, only allow a pattern style names
    | K_MBEAN mbean
    | K_MBEANS mbean
    ;

roleResource
    : K_ALL K_ROLES
    | K_ROLE  userOrRoleName
    ;

functionResource

    : K_ALL K_FUNCTIONS
    | K_ALL K_FUNCTIONS K_IN K_KEYSPACE  keyspaceName
    // Arg types are mandatory for DCL statements on Functions
    | K_FUNCTION functionName
      (
        '('
          (
            comparatorType
            ( ',' comparatorType  )*
          )?
        ')'
      )

    ;

/**
 * CREATE USER [IF NOT EXISTS] <username> [WITH PASSWORD <password>] [SUPERUSER|NOSUPERUSER]
 */
createUserStatement

    : K_CREATE K_USER (K_IF K_NOT K_EXISTS )? username
      ( K_WITH userPassword )?
      ( K_SUPERUSER  | K_NOSUPERUSER  )?

    ;

/**
 * ALTER USER [IF EXISTS] <username> [WITH PASSWORD <password>] [SUPERUSER|NOSUPERUSER]
 */
alterUserStatement

    : K_ALTER K_USER (K_IF K_EXISTS )? username
      ( K_WITH userPassword )?
      ( K_SUPERUSER
        | K_NOSUPERUSER  ) ?

    ;

/**
 * DROP USER [IF EXISTS] <username>
 */
dropUserStatement

    : K_DROP K_USER (K_IF K_EXISTS )? username
    ;
/**
 * ADD IDENTITY [IF NOT EXISTS] <identity> TO ROLE <role>
 */
addIdentityStatement

    : K_ADD K_IDENTITY (K_IF K_NOT K_EXISTS )? identity  K_TO K_ROLE identity
    ;

/**
 * DROP IDENTITY [IF EXISTS] <identity>
 */
 dropIdentityStatement

      : K_DROP K_IDENTITY (K_IF K_EXISTS )? identity
      ;

/**
 * LIST USERS
 */
listUsersStatement
    : K_LIST K_USERS
    ;

/**
 * CREATE ROLE [IF NOT EXISTS] <rolename> [ [WITH] option [ [AND] option ]* ]
 *
 * where option can be:
 *  PASSWORD = '<password>'
 *  SUPERUSER = (true|false)
 *  LOGIN = (true|false)
 *  OPTIONS = { 'k1':'v1', 'k2':'v2'}
 *  ACCESS TO ALL DATACENTERS
 *  ACCESS TO DATACENTERS { dcPermission (, dcPermission)* }
 *  ACCESS FROM ALL CIDRS
 *  ACCESS FROM CIDRS { cidrPermission (, cidrPermission)* }
 */
createRoleStatement

    : K_CREATE K_ROLE (K_IF K_NOT K_EXISTS )? userOrRoleName
      ( K_WITH roleOptions )?

    ;

/**
 * ALTER ROLE [IF EXISTS] <rolename> [ [WITH] option [ [AND] option ]* ]
 *
 * where option can be:
 *  PASSWORD = '<password>'
 *  SUPERUSER = (true|false)
 *  LOGIN = (true|false)
 *  OPTIONS = { 'k1':'v1', 'k2':'v2'}
 *  ACCESS TO ALL DATACENTERS
 *  ACCESS TO DATACENTERS { dcPermission (, dcPermission)* }
 *  ACCESS FROM ALL CIDRS
 *  ACCESS FROM CIDRS { cidrPermission (, cidrPermission)* }
 */
alterRoleStatement

    : K_ALTER K_ROLE (K_IF K_EXISTS )? userOrRoleName
      ( K_WITH roleOptions )?

    ;

/**
 * DROP ROLE [IF EXISTS] <rolename>
 */
dropRoleStatement

    : K_DROP K_ROLE (K_IF K_EXISTS )? userOrRoleName

    ;

/**
 * LIST ROLES [OF <rolename>] [NORECURSIVE]
 */
listRolesStatement

    : K_LIST K_ROLES
      ( K_OF roleName)?
      ( K_NORECURSIVE  )?

    ;

roleOptions
    : roleOption (K_AND roleOption)*
    ;

roleOption
    :  K_PASSWORD '=' STRING_LITERAL
    |  K_HASHED K_PASSWORD '=' STRING_LITERAL
    |  K_OPTIONS '=' fullMapLiteral
    |  K_SUPERUSER '=' BOOLEAN
    |  K_LOGIN '=' BOOLEAN
    |  K_ACCESS K_TO K_ALL K_DATACENTERS
    |  K_ACCESS K_TO K_DATACENTERS '{' dcPermission (',' dcPermission)* '}'
    |  K_ACCESS K_FROM K_ALL K_CIDRS
    |  K_ACCESS K_FROM K_CIDRS '{' cidrPermission (',' cidrPermission)* '}'
    ;

dcPermission
    : STRING_LITERAL
    ;

cidrPermission
    : STRING_LITERAL
    ;

// for backwards compatibility in CREATE/ALTER USER, this has no '='
userPassword
    :  K_PASSWORD STRING_LITERAL
    |  K_HASHED K_PASSWORD STRING_LITERAL
    ;

/**
 * DESCRIBE statement(s)
 *
 * Must be in sync with the javadoc for org.apache.cassandra.cql3.statements.DescribeStatement and the
 * cqlsh syntax definition in for cqlsh_describe_cmd_syntax_rules pylib/cqlshlib/cqlshhandling.py.
 */
describeStatement

    : ( K_DESCRIBE | K_DESC )
    (  K_CLUSTER
    | (K_FULL )? K_SCHEMA
    |  K_KEYSPACES
    | (K_ONLY )? K_KEYSPACE ( keyspaceName )?

    |  K_TABLES
    | K_COLUMNFAMILY columnFamilyName
    | K_INDEX columnFamilyName
    | K_MATERIALIZED K_VIEW columnFamilyName
    |  K_TYPES
    | K_TYPE userTypeName
    |  K_FUNCTIONS
    | K_FUNCTION functionName
    |  K_AGGREGATES
    | K_AGGREGATE functionName
    | ( ( IDENT
          | QUOTED_NAME
          | unreserved_keyword           ) '.' )?
        ( IDENT
        | QUOTED_NAME
        | unreserved_keyword              )

    )
    ( K_WITH K_INTERNALS  )?
    ;

/** DEFINITIONS **/

// Like ident, but for case where we take a column name that can be the legacy super column empty name. Importantly,
// this should not be used in DDL statements, as we don't want to let users create such column.
cident
    : EMPTY_QUOTED_NAME
    | ident
    ;

ident
    : IDENT
    | QUOTED_NAME
    | unreserved_keyword
    ;

fident
    : IDENT
    | QUOTED_NAME
    | unreserved_keyword
    ;

// Identifiers that do not refer to columns
noncol_ident
    : IDENT
    | QUOTED_NAME
    | unreserved_keyword
    ;

// Keyspace & Column family names
keyspaceName

    : ksName
    ;

indexName

    : (ksName '.')? idxName
    ;

columnFamilyName

    : (ksName '.')? cfName
    ;

userTypeName
    : (noncol_ident '.')? non_type_ident
    ;

userOrRoleName

    : roleName
    ;

ksName
    : IDENT
    | QUOTED_NAME
    | unreserved_keyword
    | QMARK
    ;

cfName
    : IDENT
    | QUOTED_NAME
    | unreserved_keyword
    | QMARK
    ;

idxName
    : IDENT
    | QUOTED_NAME
    | unreserved_keyword
    | QMARK
    ;

roleName
    : IDENT
    | STRING_LITERAL
    | QUOTED_NAME
    | unreserved_keyword
    | QMARK
    ;

constant
    : STRING_LITERAL
    | INTEGER
    | FLOAT
    | BOOLEAN
    | DURATION
    | UUID
    | HEXNUMBER
    | ((K_POSITIVE_NAN | K_NEGATIVE_NAN)
        | K_POSITIVE_INFINITY
        | K_NEGATIVE_INFINITY )
    ;

fullMapLiteral

    : '{' ( term ':' term  ( ',' term ':' term  )* )?
      '}'
    ;

setOrMapLiteral
    : mapLiteral
    | setLiteral
    ;

setLiteral

    : ( ',' term  )*
    ;

mapLiteral

    : ':' term  ( ',' term ':' term  )*
    ;

collectionLiteral
    : listLiteral
    | '{' term setOrMapLiteral  '}'
    // Note that we have an ambiguity between maps and set for "{}". So we force it to a set literal,
    // and deal with it later based on the type of the column (SetLiteral.java).
    | '{' '}'
    ;

listLiteral

    : '[' ( term  ( ',' term  )* )? ']'
    ;

usertypeLiteral

    // We don't allow empty literals because that conflicts with sets/maps and is currently useless since we don't allow empty user types
    : '{' fident ':' term  ( ',' fident ':' term  )* '}'
    ;

tupleLiteral

    : '(' term  ( ',' term  )* ')'
    ;

value
    : constant
    | collectionLiteral
    | usertypeLiteral
    | tupleLiteral
    | K_NULL
    | ':' noncol_ident
    | QMARK
    ;

intValue
    : INTEGER
    | ':' noncol_ident
    | QMARK
    ;

functionName
     // antlr might try to recover and give a null for f. It will still error out in the end, but FunctionName
     // wouldn't be happy with that so we should bypass this for now or we'll have a weird user-facing error
    : (keyspaceName '.')? allowedFunctionName
    ;

allowedFunctionName
    : IDENT
    | QUOTED_NAME
    | unreserved_function_keyword
    | K_TOKEN
    | K_COUNT
    ;

function
    : functionName '(' ')'
    | functionName '(' functionArgs ')'
    ;

functionArgs

    : term  ( ',' term  )*
    ;

term
    : termAddition
    ;

termAddition
    :   termMultiplication
        ( '+' termMultiplication
        | '-' termMultiplication
        )*
    ;

termMultiplication
    :   termGroup
        ( '*' termGroup
        | '/' termGroup
        | '%' termGroup
        )*
    ;

termGroup
    : simpleTerm
    | '-'  simpleTerm
    ;

simpleTerm
    : value
    | function
    | '(' comparatorType ')' simpleTerm
    | K_CAST '(' simpleTerm K_AS native_type ')'
    ;

columnOperation
    : cident columnOperationDifferentiator
    ;

columnOperationDifferentiator
    : '=' normalColumnOperation
    | shorthandColumnOperation
    | '[' term ']' collectionColumnOperation
    | '.' fident udtColumnOperation
    ;

normalColumnOperation
    : term ('+' cident )?

    | cident ('+' | '-') term

    | cident INTEGER

    ;

shorthandColumnOperation
    : ('+=' | '-=') term

    ;

collectionColumnOperation
    : '=' term

    ;

udtColumnOperation
    : '=' term

    ;

columnCondition
    // Note: we'll reject duplicates later
    : cident
        ( relationType term
        | containsOperator term
        | K_IN
            ( singleColumnInValues
            | inMarker
            )
        | '[' term ']'
            ( relationType term
            | K_IN
                ( singleColumnInValues
                | inMarker
                )
            )
        | '.' fident
            ( relationType term
            | K_IN
                ( singleColumnInValues
                | inMarker
                )
            )
        )
    ;

properties
    : property (K_AND property)*
    ;

property
    : noncol_ident '=' propertyValue
    | noncol_ident '=' fullMapLiteral
    ;

propertyValue
    : constant
    | unreserved_keyword
    ;

relationType
    : '='
    | '<'
    | '<='
    | '>'
    | '>='
    | '!='
    ;

relation
    : cident relationType term
    | cident K_LIKE term
    | cident K_IS K_NOT K_NULL
    | K_TOKEN tupleOfIdentifiers relationType term

    | cident K_IN inMarker

    | cident K_IN singleColumnInValues

    | cident containsOperator term
    | cident '[' term ']' relationType term
    | tupleOfIdentifiers
      ( K_IN
          ( '(' ')'

          | inMarkerForTuple /* (a, b, c) IN ? */

          | tupleOfTupleLiterals /* (a, b, c) IN ((1, 2, 3), (4, 5, 6), ...) */

          | tupleOfMarkersForTuples /* (a, b, c) IN (?, ?, ...) */

          )
      | relationType tupleLiteral /* (a, b, c) > (1, 2, 3) or (a, b, c) > (?, ?, ?) */

      | relationType markerForTuple /* (a, b, c) >= ? */

      )
    | '(' relation ')'
    ;

containsOperator
    : K_CONTAINS  (K_KEY )?
    ;

inMarker
    : QMARK
    | ':' noncol_ident
    ;

tupleOfIdentifiers

    : '(' cident  (',' cident )* ')'
    ;

singleColumnInValues

    : '(' (  term  (',' term )* )? ')'
    ;

tupleOfTupleLiterals

    : '(' tupleLiteral  (',' tupleLiteral )* ')'
    ;

markerForTuple
    : QMARK
    | ':' noncol_ident
    ;

tupleOfMarkersForTuples

    : '(' markerForTuple  (',' markerForTuple )* ')'
    ;

inMarkerForTuple
    : QMARK
    | ':' noncol_ident
    ;

comparatorType
    : native_type
    | collection_type
    | tuple_type
    | vector_type
    | userTypeName
    | K_FROZEN '<' comparatorType '>'

    | STRING_LITERAL

    ;

native_type
    : K_ASCII
    | K_BIGINT
    | K_BLOB
    | K_BOOLEAN
    | K_COUNTER
    | K_DECIMAL
    | K_DOUBLE
    | K_DURATION
    | K_FLOAT
    | K_INET
    | K_INT
    | K_SMALLINT
    | K_TEXT
    | K_TIMESTAMP
    | K_TINYINT
    | K_UUID
    | K_VARCHAR
    | K_VARINT
    | K_TIMEUUID
    | K_DATE
    | K_TIME
    ;

collection_type
    : K_MAP  '<' comparatorType ',' comparatorType '>'

    | K_LIST '<' comparatorType '>'

    | K_SET  '<' comparatorType '>'

    ;

tuple_type

    : K_TUPLE '<' comparatorType  (',' comparatorType )* '>'
    ;

vector_type
    : K_VECTOR '<' comparatorType ','  INTEGER '>'

    ;

username
    : IDENT
    | STRING_LITERAL
    | QUOTED_NAME
    ;

identity
    : IDENT
    | STRING_LITERAL
    | QUOTED_NAME
    ;

mbean
    : STRING_LITERAL
    ;

// Basically the same as cident, but we need to exlude existing CQL3 types
// (which for some reason are not reserved otherwise)
non_type_ident
    : IDENT
    | QUOTED_NAME
    | basic_unreserved_keyword
    | K_KEY
    ;

unreserved_keyword
    : unreserved_function_keyword
    | (K_TTL | K_COUNT | K_WRITETIME | K_MAXWRITETIME | K_KEY | K_CAST | K_JSON | K_DISTINCT)
    ;

unreserved_function_keyword
    : basic_unreserved_keyword
    | native_type
    ;

basic_unreserved_keyword
    : ( K_KEYS
        | K_AS
        | K_CLUSTER
        | K_CLUSTERING
        | K_COMPACT
        | K_STORAGE
        | K_TABLES
        | K_TYPE
        | K_TYPES
        | K_VALUES
        | K_MAP
        | K_LIST
        | K_FILTERING
        | K_PERMISSION
        | K_PERMISSIONS
        | K_KEYSPACES
        | K_ALL
        | K_USER
        | K_USERS
        | K_ROLE
        | K_ROLES
        | K_IDENTITY
        | K_SUPERUSER
        | K_NOSUPERUSER
        | K_LOGIN
        | K_NOLOGIN
        | K_OPTIONS
        | K_PASSWORD
        | K_HASHED
        | K_EXISTS
        | K_CUSTOM
        | K_TRIGGER
        | K_CONTAINS
        | K_INTERNALS
        | K_ONLY
        | K_STATIC
        | K_FROZEN
        | K_TUPLE
        | K_FUNCTION
        | K_FUNCTIONS
        | K_AGGREGATE
        | K_AGGREGATES
        | K_SFUNC
        | K_STYPE
        | K_FINALFUNC
        | K_INITCOND
        | K_RETURNS
        | K_LANGUAGE
        | K_CALLED
        | K_INPUT
        | K_LIKE
        | K_PER
        | K_PARTITION
        | K_GROUP
        | K_DATACENTERS
        | K_CIDRS
        | K_ACCESS
        | K_DEFAULT
        | K_MBEAN
        | K_MBEANS
        | K_REPLACE
        | K_UNSET
        | K_MASKED
        | K_UNMASK
        | K_SELECT_MASKED
        | K_VECTOR
        | K_ANN
        )
    ;
