name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  LOG_LEVEL: DEBUG
  CASSANDRA_LOG_LEVEL: DEBUG

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - name: Check formatting, scalafix, and headers
        run: sbt styleCheck

      - name: Check MiMa
        run: sbt mimaReportBinaryIssues

      - name: Check docs
        run: sbt docs/mdoc

      - name: Test Coverage
        run: sbt testCoverage
